[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmer = "*"
anyhow = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }